In [1]:
import pandas as pd
import numpy as np

In [16]:
# connecting to gdrive
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)
gdrive_path = f"/content/gdrive/MyDrive/ds/"

Mounted at /content/gdrive

In [18]:
# reading dataset to pandas dataframe
data = pd.read_csv("/content/gdrive/MyDrive/ds/Cancer_rate_by_countries.csv", index_col=0)
# show first 20 rows
data.head(20)

    Rank                 Country  Cancer_Rate
0      1               Australia        468.0
1      2             New Zealand        438.1
2      3                 Ireland        373.7
3      4                 Hungary        368.1
4      5           United States        352.2
5      6                 Belgium        345.8
6      7                  France        344.1
7      8                 Denmark        340.4
8      9                  Norway        337.8
9     10             Netherlands        334.1
10    11                  Canada        334.0
11    12  France (New Caledonia)        324.2
12    13          United Kingdom        319.2
13    14             South Korea        313.5
14    15                 Germany        313.1
15    16             Switzerland        311.0
16    17              Luxembourg        309.3
17    18                  Serbia        307.9
18    19                Slovenia        304.9
19    20                  Latvia        302.2

In [4]:
# show dataframe general info
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Rank         50 non-null     int64
 1   Country      50 non-null     object
 2   Cancer_Rate  50 non-null     float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.6+ KB

Dataset has 3 columns and all rows are filled with values

In [5]:
# show dataframe column Cancer_Rate
data.Cancer_Rate

0     468.0
1     438.1
2     373.7
3     368.1
4     352.2
5     345.8
6     344.1
7     340.4
8     337.8
9     334.1
10    334.0
11    324.2
12    319.2
13    313.5
14    313.1
15    311.0
16    309.3
17    307.9
18    304.9
19    302.2
20    297.5
21    296.7
22    294.7
23    290.6
24    287.2
25    285.8
26    283.3
27    279.8
28    272.3
29    266.2
30    263.4
31    260.7
32    259.5
33    257.8
34    254.6
35    254.5
36    254.2
37    253.8
38    250.8
39    250.8
40    249.4
41    248.9
42    248.0
43    247.7
44    247.5
45    247.0
46    242.8
47    242.8
48    240.6
49    233.6
Name: Cancer_Rate, dtype: float64

In [17]:
# show columns description 
data.Cancer_Rate.describe()

count     50.000000
mean     294.082000
std       50.026628
min      233.600000
25%      253.900000
50%      286.500000
75%      317.775000
max      468.000000
Name: Cancer_Rate, dtype: float64

Column has a numerical data type, thus description shows its size, mean, standard deviation, min and max, and quartiles.

In [6]:
data.Country.describe()

count            50
unique           50
top       Australia
freq              1
Name: Country, dtype: object

Column has a string data type, thus description shows its size, number of unique values, the most frequent entry, and its frequency.

In [7]:
# show column mean value
data.Cancer_Rate.mean()

294.08200000000005

In [8]:
# show a list of column's unique values
data.Country.unique()

array(['Australia', 'New Zealand', 'Ireland', 'Hungary', 'United States',
       'Belgium', 'France', 'Denmark', 'Norway', 'Netherlands', 'Canada',
       'France (New Caledonia)', 'United Kingdom', 'South Korea',
       'Germany', 'Switzerland', 'Luxembourg', 'Serbia', 'Slovenia',
       'Latvia', 'Slovakia', 'Czech Republic', 'Sweden', 'Italy',
       'Croatia', 'Lithuania', 'Estonia', 'Greece', 'Spain', 'Finland',
       'Uruguay', 'Belarus', 'Portugal', 'Iceland', 'France (Guadeloupe)',
       'United States (Puerto Rico)', 'Moldova', 'Poland', 'Cyprus',
       'France (Martinique)', 'Malta', 'Singapore', 'Japan', 'Austria',
       'Barbados', 'France (French Guiana)', 'Bulgaria', 'Lebanon',
       'France (French Polynesia)', 'Israel'], dtype=object)

In [9]:
# show column's entries and how many times they appear
data.Country.value_counts()

Australia                      1
Poland                         1
Greece                         1
Spain                          1
Finland                        1
Uruguay                        1
Belarus                        1
Portugal                       1
Iceland                        1
France (Guadeloupe)            1
United States (Puerto Rico)    1
Moldova                        1
Cyprus                         1
New Zealand                    1
France (Martinique)            1
Malta                          1
Singapore                      1
Japan                          1
Austria                        1
Barbados                       1
France (French Guiana)         1
Bulgaria                       1
Lebanon                        1
France (French Polynesia)      1
Estonia                        1
Lithuania                      1
Croatia                        1
Italy                          1
Ireland                        1
Hungary                        1
United States                  1
Belgium                        1
France                         1
Denmark                        1
Norway                         1
Netherlands                    1
Canada                         1
France (New Caledonia)         1
United Kingdom                 1
South Korea                    1
Germany                        1
Switzerland                    1
Luxembourg                     1
Serbia                         1
Slovenia                       1
Latvia                         1
Slovakia                       1
Czech Republic                 1
Sweden                         1
Israel                         1
Name: Country, dtype: int64

In [12]:
# create a column of mapped values from another column series by substracting 
# column's mean value from all its rows
cancer_mean = data.Cancer_Rate.mean()
data["Cancer_div"] = data.Cancer_Rate.map(lambda p: p - cancer_mean)
data

    Rank                      Country  Cancer_Rate  Cancer_div
0      1                    Australia        468.0     173.918
1      2                  New Zealand        438.1     144.018
2      3                      Ireland        373.7      79.618
3      4                      Hungary        368.1      74.018
4      5                United States        352.2      58.118
5      6                      Belgium        345.8      51.718
6      7                       France        344.1      50.018
7      8                      Denmark        340.4      46.318
8      9                       Norway        337.8      43.718
9     10                  Netherlands        334.1      40.018
10    11                       Canada        334.0      39.918
11    12       France (New Caledonia)        324.2      30.118
12    13               United Kingdom        319.2      25.118
13    14                  South Korea        313.5      19.418
14    15                      Germany        313.1      19.018
15    16                  Switzerland        311.0      16.918
16    17                   Luxembourg        309.3      15.218
17    18                       Serbia        307.9      13.818
18    19                     Slovenia        304.9      10.818
19    20                       Latvia        302.2       8.118
20    21                     Slovakia        297.5       3.418
21    22               Czech Republic        296.7       2.618
22    23                       Sweden        294.7       0.618
23    24                        Italy        290.6      -3.482
24    25                      Croatia        287.2      -6.882
25    26                    Lithuania        285.8      -8.282
26    27                      Estonia        283.3     -10.782
27    28                       Greece        279.8     -14.282
28    29                        Spain        272.3     -21.782
29    30                      Finland        266.2     -27.882
30    31                      Uruguay        263.4     -30.682
31    32                      Belarus        260.7     -33.382
32    33                     Portugal        259.5     -34.582
33    34                      Iceland        257.8     -36.282
34    35          France (Guadeloupe)        254.6     -39.482
35    36  United States (Puerto Rico)        254.5     -39.582
36    37                      Moldova        254.2     -39.882
37    38                       Poland        253.8     -40.282
38    39                       Cyprus        250.8     -43.282
39    40          France (Martinique)        250.8     -43.282
40    41                        Malta        249.4     -44.682
41    42                    Singapore        248.9     -45.182
42    43                        Japan        248.0     -46.082
43    44                      Austria        247.7     -46.382
44    45                     Barbados        247.5     -46.582
45    46       France (French Guiana)        247.0     -47.082
46    47                     Bulgaria        242.8     -51.282
47    48                      Lebanon        242.8     -51.282
48    49    France (French Polynesia)        240.6     -53.482
49    50                       Israel        233.6     -60.482

Above is Cancer Rate diviation next to Cancer Rate

In [13]:
# function to make Country column entries in the upper case, and 
# reset Cancer_div to the absolute values (negatives change to positives)
def remean_points(row):
    row.Cancer_div = np.abs(row.Cancer_Rate - cancer_mean)
    row.Country = row.Country.upper()
    return row

# applying the defined function to all dataframe rows
data = data.apply(remean_points, axis=1)
data

    Rank                      Country  Cancer_Rate  Cancer_div
0      1                    AUSTRALIA        468.0     173.918
1      2                  NEW ZEALAND        438.1     144.018
2      3                      IRELAND        373.7      79.618
3      4                      HUNGARY        368.1      74.018
4      5                UNITED STATES        352.2      58.118
5      6                      BELGIUM        345.8      51.718
6      7                       FRANCE        344.1      50.018
7      8                      DENMARK        340.4      46.318
8      9                       NORWAY        337.8      43.718
9     10                  NETHERLANDS        334.1      40.018
10    11                       CANADA        334.0      39.918
11    12       FRANCE (NEW CALEDONIA)        324.2      30.118
12    13               UNITED KINGDOM        319.2      25.118
13    14                  SOUTH KOREA        313.5      19.418
14    15                      GERMANY        313.1      19.018
15    16                  SWITZERLAND        311.0      16.918
16    17                   LUXEMBOURG        309.3      15.218
17    18                       SERBIA        307.9      13.818
18    19                     SLOVENIA        304.9      10.818
19    20                       LATVIA        302.2       8.118
20    21                     SLOVAKIA        297.5       3.418
21    22               CZECH REPUBLIC        296.7       2.618
22    23                       SWEDEN        294.7       0.618
23    24                        ITALY        290.6       3.482
24    25                      CROATIA        287.2       6.882
25    26                    LITHUANIA        285.8       8.282
26    27                      ESTONIA        283.3      10.782
27    28                       GREECE        279.8      14.282
28    29                        SPAIN        272.3      21.782
29    30                      FINLAND        266.2      27.882
30    31                      URUGUAY        263.4      30.682
31    32                      BELARUS        260.7      33.382
32    33                     PORTUGAL        259.5      34.582
33    34                      ICELAND        257.8      36.282
34    35          FRANCE (GUADELOUPE)        254.6      39.482
35    36  UNITED STATES (PUERTO RICO)        254.5      39.582
36    37                      MOLDOVA        254.2      39.882
37    38                       POLAND        253.8      40.282
38    39                       CYPRUS        250.8      43.282
39    40          FRANCE (MARTINIQUE)        250.8      43.282
40    41                        MALTA        249.4      44.682
41    42                    SINGAPORE        248.9      45.182
42    43                        JAPAN        248.0      46.082
43    44                      AUSTRIA        247.7      46.382
44    45                     BARBADOS        247.5      46.582
45    46       FRANCE (FRENCH GUIANA)        247.0      47.082
46    47                     BULGARIA        242.8      51.282
47    48                      LEBANON        242.8      51.282
48    49    FRANCE (FRENCH POLYNESIA)        240.6      53.482
49    50                       ISRAEL        233.6      60.482

Above is Cancer Rate diviation absolute values next to Cancer Rate

In [14]:
# show difference between a Cancer_rate series and its mean
data.Cancer_Rate - cancer_mean

0     173.918
1     144.018
2      79.618
3      74.018
4      58.118
5      51.718
6      50.018
7      46.318
8      43.718
9      40.018
10     39.918
11     30.118
12     25.118
13     19.418
14     19.018
15     16.918
16     15.218
17     13.818
18     10.818
19      8.118
20      3.418
21      2.618
22      0.618
23     -3.482
24     -6.882
25     -8.282
26    -10.782
27    -14.282
28    -21.782
29    -27.882
30    -30.682
31    -33.382
32    -34.582
33    -36.282
34    -39.482
35    -39.582
36    -39.882
37    -40.282
38    -43.282
39    -43.282
40    -44.682
41    -45.182
42    -46.082
43    -46.382
44    -46.582
45    -47.082
46    -51.282
47    -51.282
48    -53.482
49    -60.482
Name: Cancer_Rate, dtype: float64

In [15]:
# concat Country and stringified Rank values
data.Country + " " + data.Rank.astype("string")

0                        AUSTRALIA 1
1                      NEW ZEALAND 2
2                          IRELAND 3
3                          HUNGARY 4
4                    UNITED STATES 5
5                          BELGIUM 6
6                           FRANCE 7
7                          DENMARK 8
8                           NORWAY 9
9                     NETHERLANDS 10
10                         CANADA 11
11         FRANCE (NEW CALEDONIA) 12
12                 UNITED KINGDOM 13
13                    SOUTH KOREA 14
14                        GERMANY 15
15                    SWITZERLAND 16
16                     LUXEMBOURG 17
17                         SERBIA 18
18                       SLOVENIA 19
19                         LATVIA 20
20                       SLOVAKIA 21
21                 CZECH REPUBLIC 22
22                         SWEDEN 23
23                          ITALY 24
24                        CROATIA 25
25                      LITHUANIA 26
26                        ESTONIA 27
27                         GREECE 28
28                          SPAIN 29
29                        FINLAND 30
30                        URUGUAY 31
31                        BELARUS 32
32                       PORTUGAL 33
33                        ICELAND 34
34            FRANCE (GUADELOUPE) 35
35    UNITED STATES (PUERTO RICO) 36
36                        MOLDOVA 37
37                         POLAND 38
38                         CYPRUS 39
39            FRANCE (MARTINIQUE) 40
40                          MALTA 41
41                      SINGAPORE 42
42                          JAPAN 43
43                        AUSTRIA 44
44                       BARBADOS 45
45         FRANCE (FRENCH GUIANA) 46
46                       BULGARIA 47
47                        LEBANON 48
48      FRANCE (FRENCH POLYNESIA) 49
49                         ISRAEL 50
dtype: string